### PR TITLE
first attempt to reorg test

### PR DESCRIPTION
**Pull request by mschoch**
first attempt to rework the tests

- previous test moved into helper func
- `connector` and `connect_to` dirs are wiped before each run
- new test `once` runs the original test func once (passes)
- new test `twice` runs the original tets func twice (fails, but not for same reasons as before, still investigating)

### CODE REVIEW

**Comment by jchris** [comment]
I think we should merge, based on reading the code, but I'm not sure if we lost the hang...

Screenshot 2024-08-12 at 7 52 08 AM

**Comment by mschoch** [comment]
@jchris I think this hangs reliably for me now.

NOTE: one of the changes I made was to explicitly "forget" cached database instances between the invocations of the main testing function (that was causing the not-found you noted above)

**Comment by jchris** [comment]
nice. it would be good to articulate the "story" this test corresponds to, maybe in comments in the test code? just to make sure its realistic / something we want to support, or maybe it needs tweaks to align with a real usage story

**Comment by mschoch** [comment]
Sure, so I'll explain it as I understand it, but we should get @mabels to review, as I still have gaps in "why" this test does some of what it does.  Also, I modified it an attempt to make it hang reliably, it's possible I've pushed further into an unsupported corner along the way...

The main test logic at the moment is as follows

- invocation 0
  - open named database "my-database" with file storage in "dist/connector"
  - connect database to another file store in "dist/connect_to"
  - write values to 3 random keys
  - read back these values, assert correct
  - read all docs, assert length >= 3
  - wait for walstore queue to idle (presumably signaling sync complete from the sender side)
  - databases file store is destroyed (deletes files, not sure what else, I'm not sure of the intent here originally)
  - new unnamed database is crated, with file store pointing to the destination of the previous connection "dist/connect_to"
  - read all docs, assert length >= 3
  - use keys from all docs, assert expected key/vals
- ADDED BY MARTY, reset fireproof.Database.databases (the second invocation was reusing the db with destroyed store)
- invocation 1 (repeats the logic above a second time) and hangs

**Comment by jchris** [comment]
Just read through those steps and it seems like there is too much there to think about. Is it possible to cut it down to fewer and fewer steps to reproduce? Alternatively, can we start writing non-hanging tests for basic scenarios?

**Comment by mschoch** [comment]
> Just read through those steps and it seems like there is too much there to think about. Is it possible to cut it down to fewer and fewer steps to reproduce? 

I can try, but I moved on to other things.

> Alternatively, can we start writing non-hanging tests for basic scenarios?

This is on my todo list.

**Comment by mschoch** [comment]
While we still need to revisit this test, enough has changed in the interim that this PR is no longer useful.

**Pull request closed without merging**
