### PR TITLE
first pass partykit connector

### PR DESCRIPTION
**Pull request by mschoch**
initial testing in progress

This is a WIP, feel free to browser for general direction, but it is not ready for review.

### CODE REVIEW

**Comment by jchris** [comment]
that looks like it could work, which is a great start!

**Comment by jchris** [comment]
Here is my test output from a first run against the core commit I mentioned on the super this pr https://gist.github.com/jchris/1c5aeb0944fea9eeb8a66c4e761c8d76

https://github.com/fireproof-storage/fireproof/pull/183#issuecomment-2322942861

**Comment by jchris** [comment]
ok I got the tests to pass beyond the `put` issue by building Fireproof core with a lower default threshold value (`5 * 1000` instead of `1000 * 1000`) here is the output https://gist.github.com/jchris/3e0cbc8e2f2e12437f090c740aa403aa

**Comment by jchris** [comment]
Screenshot 2024-08-31 at 9 55 16 AM

here is the full diff in core required

**Comment by jchris** [comment]
This will be even simpler with the meta info added in core #202

**Comment by mschoch** [comment]
This has been superceded by #19

**Pull request closed without merging**
