### PR TITLE
publishing separate packages

### PR DESCRIPTION
**Pull request by mschoch**
Initial steps toward publishing separate packages for the various gateways, using a similar approach to the main Fireproof repo.

### CODE REVIEW

**Comment by mschoch** [comment]
@jchris here is some intermediate progress to check my direcion.

Now, when you run `pnpm build` in the connect repo, more things happen:

```
❯ pnpm build

> @fireproof/connector@1.0.0 prebuild /Users/mschoch/connect
> rm -rf dist


> @fireproof/connector@1.0.0 build /Users/mschoch/connect
> pnpm run '/^build:/' && pnpm run '/^pub:/'

. build:tsc$ tsc
└─ Done in 1.6s
. build:tsup$ tsup
[21 lines collapsed]
│ [@FIREPROOF/NETLIFY] IIFE dist/netlify/index.global.js     83.00 B
│ [@FIREPROOF/NETLIFY] IIFE dist/netlify/index.global.js.map 71.00 B
│ [@FIREPROOF/NETLIFY] IIFE ⚡️ Build success in 8ms
│ [@FIREPROOF/NETLIFY] DTS Build start
│ [@FIREPROOF/NETLIFY] DTS Build start
│ [@FIREPROOF/NETLIFY] DTS ⚡️ Build success in 585ms
│ [@FIREPROOF/NETLIFY] DTS dist/netlify/index.d.ts 37.00 B
│ [@FIREPROOF/NETLIFY] DTS ⚡️ Build success in 806ms
│ [@FIREPROOF/NETLIFY] DTS dist/netlify/index.d.ts  37.00 B
│ [@FIREPROOF/NETLIFY] DTS dist/netlify/index.d.cts 37.00 B
└─ Done in 1.3s
. pub:noop$ echo
└─ Done in 10ms
. pub:netlify$ tsx ./version-copy-package.ts ./dist/netlify/package-use-fireproof.json
│ Dependency js-base64 not found in main package.json
│ Patch version 0.0.0-smoke in package.json
│ Copied package-use-fireproof.json to ./dist/netlify with version 0.0.0-smoke
│ $ cd ./dist/netlify && pnpm pack
│ fireproof-netlify-0.0.0-smoke.tgz
└─ Done in 299ms
❯ ls dist
netlify tsc
❯ ls dist/netlify
LICENSE.md                        index.d.cts                       index.js.map
README.md                         index.d.ts                        metafile-cjs.json
fireproof-netlify-0.0.0-smoke.tgz index.global.js                   metafile-esm.json
index.cjs                         index.global.js.map               metafile-iife.json
index.cjs.map                     index.js                          package.json
```

**Comment by mschoch** [comment]
One thing I know is wrong is the dependencies in the `package-netlify.json`.  I used fireproof (old-structure tag) `packages/connect-netlify/package.json` as the starting point, so that the meta-data would be close.  But I then had to remove a few of the deps to get the packer to stop complaining.

My gap in knowledge is how we should properly maintain these package.json files we keep on the side.

**Comment by mschoch** [comment]
OK, I went ahead and added support for s3 as well, because I got the docker/minio setup working.  So I should be able to test out an app with those 2 tgz's installed.

**Comment by jchris** [comment]
regarding the package versions, I think the core repo does a replace in one of the steps, you wont find this "must-set" token bc we replace by https://github.com/search?q=repo%3Afireproof-storage%2Ffireproof+%22must-set%22&type=code version here https://github.com/fireproof-storage/fireproof/blob/acbbd04c1af2646ea0572088a95cf5337e4e7281/version-copy-package.ts#L20

**Comment by mschoch** [comment]
I'm not concerned with the version.

I'm concerned with managing the dependencies.  As a developer, let's say I updated to some new version of PartyKit.  The main repo package.json will be updated.  But right now, if you want the resulting partykit-gateway package JSON to be updated, you'd have to manually edit package-partykit.json.  That seems error-prone to me.

**Pull request merged**
