### PR TITLE
netlify gateway tests pass for me now

### PR DESCRIPTION
**Pull request by mschoch**
but several open questions

### CODE REVIEW

**Comment by mschoch** [comment]
Here is a rough summary:

- When I started yesterday, I first observed a URL naming mismatch between the gateway and the server code.  The gateway was preparing urls of the form `/${store}/${key}` and the server was expecting urls with ?car=key or ?meta=main.
- As last I heard @jchris wanted backwards compat with the old servers (to the extent possible), I maintained the server URL expectations and update the gateway to match
- The netlify blobs API is somewhat limiting, and our only way to delete in bulk is to use the list operation.  I went ahead and wired this up, but I have concerns with out the destroy operation can work properly in practice.
- I also observed that GET/PUT meta were getting an array of CRDTEntries, and not a single one as the code expected.  In most places I just tacked on `[0]` which doesn't seem generally right.
- In at least one place I have hard-coded `main` which also doesn't seem right.
- Destroy should be DB operation, but it seems like as currently implemented it could wipe all databases in the app (but seems like PartyKit might also have the same issue, not scoped in $name in any way I can tell)

**Comment by jchris** [comment]
Would be cool
To have a test that destroy only gets the one db

reviewing now

**Comment by jchris** [comment]
The [0] thing is due to https://github.com/fireproof-storage/fireproof/pull/212 and expected. Maybe we can clean up once we are green everywhere but I think it’s right

**Comment by jchris** [comment]
this got aws tests passing, will look at netlify next

**Pull request merged**
